<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShowroomSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('showrooms')->insert([
            // FEATURED MODELS
            [
                'title'  => 'Kijang Innova Zenix',
                'description' => 'Cross into the new energy with bold design and advanced tech.',
                'price'       => 400000000,
                'image'       => 'zenix1.png',
                'featured'    => true,
                'specs'       => "Mesin: 2.0L Hybrid\nTransmisi: Automatic CVT\nWarna: Silver, White, Black\nKapasitas: 7 penumpang\nFitur Keamanan: ABS, EBD, Dual SRS Airbags",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Avanza Veloz',
                'description' => 'Refined design, modern features, and improved efficiency.',
                'price'       => 250000000,
                'image'       => 'veloz.png',
                'featured'    => true,
                'specs'       => "Mesin: 1.5L Dual VVT-i\nTransmisi: CVT / Manual\nWarna: Red Mica Metallic, Black Metallic\nKapasitas: 7 penumpang\nFitur: Keyless Entry, Start/Stop Engine",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'All New Toyota GR86',
                'description' => 'Bred from racing DNA, built for pure driving excitement.',
                'price'       => 850000000,
                'image'       => 'gr.png',
                'featured'    => true,
                'specs'       => "Mesin: 2.4L Boxer\nTenaga: 228 HP\nTransmisi: 6MT / 6AT\nLayout: RWD\nFitur Sport: Limited Slip Differential, Track Mode",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Vellfire',
                'description' => 'Luxurious MPV designed for executive comfort and style.',
                'price'       => 1200000000,
                'image'       => 'vellfire.png',
                'featured'    => true,
                'specs'       => "Mesin: 2.5L\nTransmisi: CVT\nFitur: Captain Seat, Dual Sunroof, 7 SRS Airbags\nWarna: Black, White Pearl\nSuspensi Nyaman untuk VIP",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'GR Yaris',
                'description' => 'Rally-bred hot hatch designed for pure performance.',
                'price'       => 750000000,
                'image'       => 'yaris.jpeg',
                'featured'    => true,
                'specs'       => "Mesin: 1.6L Turbo 3-silinder\nTenaga: 268 HP\nSistem: AWD\nTransmisi: 6MT\nFitur: Recaro Seat, Torsen LSD",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Supra',
                'description' => 'Iconic sports car reborn with impressive power and style.',
                'price'       => 1400000000,
                'image'       => 'supra.png',
                'featured'    => true,
                'specs'       => "Mesin: 3.0L Turbo Inline-6\nTenaga: 340 HP\nTransmisi: 8AT / 6MT (baru)\nFitur Sport: Launch Control, Active Rear Diff\nWarna: Red, Matte Gray",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],

            // NORMAL MODELS
            [
                'title'  => 'Kijang Innova',
                'description' => 'Early generation MPV with legendary reliability.',
                'price'       => 200000000,
                'image'       => 'innova.png',
                'featured'    => false,
                'specs'       => "Mesin: 2.0L Gasoline\nTransmisi: Manual 5-speed\nKapasitas: 7 penumpang\nFitur Keamanan: Dual Airbags, ABS",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Kijang Innova Reborn',
                'description' => 'Improved performance and modern comfort in one package.',
                'price'       => 300000000,
                'image'       => 'reborn.png',
                'featured'    => false,
                'specs'       => "Mesin: 2.0L / 2.4L Diesel\nTransmisi: Manual / Automatic\nFitur: Touchscreen Display, AC Double Blower\nKapasitas: 7 penumpang",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Avanza',
                'description' => 'Iconic affordable MPV beloved by many families in Indonesia.',
                'price'       => 190000000,
                'image'       => 'avanza-lama.png',
                'featured'    => false,
                'specs'       => "Mesin: 1.3L / 1.5L\nTransmisi: Manual / Automatic\nWarna: Silver, Dark Red\nFitur: 2 Airbags, Audio Steering Switch",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Corolla',
                'description' => 'A global icon known for reliability, comfort, and style.',
                'price'       => 350000000,
                'image'       => 'corolla.jpg',
                'featured'    => false,
                'specs'       => "Mesin: 1.8L / 2.0L\nTransmisi: CVT\nFitur: TSS (Toyota Safety Sense), Lane Keep Assist\nKapasitas: 5 penumpang",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Rush',
                'description' => 'A rugged and spacious SUV designed for adventure.',
                'price'       => 260000000,
                'image'       => 'rush.png',
                'featured'    => false,
                'specs'       => "Mesin: 1.5L Dual VVT-i\nTransmisi: Manual / Automatic\nGround Clearance: 220mm\nFitur: 7 Airbags, Hill Start Assist",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Agya',
                'description' => 'A compact and fuel-efficient city car perfect for urban driving.',
                'price'       => 160000000,
                'image'       => 'agya.png',
                'featured'    => false,
                'specs'       => "Mesin: 1.2L\nTransmisi: Manual / Automatic\nWarna: Yellow, Gray, White\nFitur: Digital AC, Dual SRS Airbag",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Raize',
                'description' => 'A stylish compact SUV offering dynamic performance and flexibility.',
                'price'       => 220000000,
                'image'       => 'raize.jpg',
                'featured'    => false,
                'specs'       => "Mesin: 1.0L Turbo\nTransmisi: CVT\nWarna: Two-tone Red/Black, Yellow/Black\nFitur: TSS, 17-inch Alloy Wheel",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Camry',
                'description' => 'Premium sedan combining luxury, performance, and comfort.',
                'price'       => 600000000,
                'image'       => 'camry.png',
                'featured'    => false,
                'specs'       => "Mesin: 2.5L\nTransmisi: 6AT / CVT Hybrid\nFitur: Leather Seat, Electric Sunroof, TSS\nWarna: Black, White Pearl",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Alphard',
                'description' => 'High-end MPV offering maximum comfort and executive class experience.',
                'price'       => 1500000000,
                'image'       => 'alphard.jpg',
                'featured'    => false,
                'specs'       => "Mesin: 2.5L / 3.5L\nTransmisi: CVT\nFitur: Captain Seat, Dual Moonroof, Rear Entertainment\nKapasitas: 7 penumpang",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Fortuner',
                'description' => 'A robust SUV built for off-road adventures and city drive alike.',
                'price'       => 500000000,
                'image'       => 'fortuner.png',
                'featured'    => false,
                'specs'       => "Mesin: 2.4L Diesel / 2.7L Gasoline\nTransmisi: 6AT\n4x2 / 4x4\nFitur: Rear Diff Lock, 7 SRS Airbags",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'title'  => 'Toyota Vios',
                'description' => 'Compact sedan well-suited for urban commuting with excellent fuel economy.',
                'price'       => 220000000,
                'image'       => 'vios.jpg',
                'featured'    => false,
                'specs'       => "Mesin: 1.5L Dual VVT-i\nTransmisi: CVT / Manual\nFitur: ECO Mode, Paddle Shift (CVT)\nKapasitas: 5 penumpang",
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
        ]);
    }
}
